version: '3.8'
services:
  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8081
      - POSTGRES_DB_URL=jdbc:postgresql://service-db/file_server
      - POSTGRES_DB_USERNAME=postgres
      - POSTGRES_DB_PASSWORD=root
      - FILES_PATH=/file-server

  service-db:
    image: postgres:16-alpine
    environment:
#      POSTGRES_DB: file_server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "15432:5432"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./infrastructure/db/create_function.sql:/docker-entrypoint-initdb.d/create_function.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  keycloak:
    container_name: keycloak_container
    image: quay.io/keycloak/keycloak:22.0.5
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./infrastructure/sso/File-Manager-realm.json:/opt/keycloak/data/import/File-Manager-realm.json
#      - sso-data:/var/lib
    depends_on:
      - service-db

volumes:
  db-data:
  pgadmin-data: